# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft / Loader
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
neo_version=21.8.40
neo_version_range=[21.8,)
loader_version_range=[4,)

# Dependencies
rei_version=20.0.811
jei_version=24.0.0.2

# Mod identification / metadata
mod_id=tinycoal
mod_name=TinyCoal
mod_license=All Rights Reserved
mod_version=1.21.8-0.3
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=This mod lets you break Coal and Charcoal into 8 pieces that each smelt 1 item
