# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft / Loader
minecraft_version=1.21.9
minecraft_version_range=[1.21.9,1.22)
neo_version=21.9.16-beta
neo_version_range=[21.9,)
loader_version_range=[4,)

# Dependencies
rei_version=20.0.811
jei_version=24.0.0.2

# Mod identification / metadata
mod_id=tinycoal
mod_name=TinyCoal
mod_license=All Rights Reserved
mod_version=1.21.9-0.1
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=This mod lets you break Coal and Charcoal into 8 pieces that each smelt 1 item
