# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft / Loader
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
forge_version=58.0.0
forge_version_range=[58,)
loader_version_range=[58,)
mapping_channel=official
mapping_version=1.21.8

# Dependencies

# Mod identification / metadata
mod_id=tinycoal
mod_name=TinyCoal
mod_license=All-Rights-Reserved
mod_version=1.21.8-0.2
mod_group_id=com.blocklegend001
mod_authors=Block_Legend001
mod_description=This mod let you break Coal and Charcoal in 8 pieces that smelt 1 item
